import FinancingBanner from '@/components/financing-banner'; import PageHero from '@/components/page-hero'; import BookNowButton from '@/components/book-now-button'; import BookingSection from '@/components/booking-section';

const ivMenu = [
  ['Alleviate', '$140', 'Alleviate offers a specialized blend of calcium, magnesium chloride, and Vita complex, enhanced with hydrocobalamin in a 1000 ml saline solution. This carefully formulated mix is designed to support overall wellness and improve hydration, making it an ideal choice for those seeking effective nutritional supplementation.'],
  ['Athletic Performance', '$150', 'Athletic Performance services offer a specialized infusion of 5000 mcg Hydrocobalamin, a powerful form of vitamin B12, combined with a tailored Amino Blend and B-Complex for enhanced energy, recovery, and overall athletic performance. This unique blend is designed to support endurance, muscle recovery, and optimal physical function, ensuring you perform at your best.'],
  ['B-Lean', '$140', 'B-Lean offers a unique blend of Methylcobalamin, taurine, and essential vitamins designed to support energy levels and metabolic health. This carefully formulated service aims to enhance overall wellness and promote an active lifestyle through targeted nutritional support.'],
  ['Brainstorm', '$155', 'Brainstorm offers a unique infusion service that combines essential nutrients from vials of Alpha Lipoic, Taurine, and Pyridoxine. This service involves injecting the mixture into a 1000ml normal saline IV bag, providing a tailored approach to wellness.'],
  ['Cold and Flu', '$150', 'Cold and Flu services provide essential support during seasonal illnesses, utilizing a combination of ascorbic acid for immune support, vitamin complexes to replenish nutrients, and Toradol for effective pain relief. Our carefully formulated approach aims to alleviate symptoms and promote a quicker recovery, ensuring you feel your best during illness.'],
  ['Food Poisoning', '$155', 'Food Poisoning services provide essential treatments for individuals experiencing symptoms related to contaminated food. Utilizing medications like B Complex, Zofran, and Toradol, these services aim to alleviate discomfort and promote recovery from nausea, pain, and other related ailments.'],
  ['Get Up & Go', '$140', 'Get Up & Go offers an energizing blend of Vita Complex and Amino Blend, expertly drawn from vials and injected into a 1000ml normal saline (NS) bag. This service is designed to boost vitality and enhance overall wellness through a customized intravenous infusion.'],
  ['Gut Health', '$160', 'Our Gut Health service offers a specialized intravenous therapy that combines magnesium sulfate, B complex vitamins, ascorbic acid, zinc, and cobalamin IVP to support optimal digestive function and overall wellness. This carefully formulated blend aims to enhance nutrient absorption, boost immunity, and promote a balanced gut microbiome for improved health.'],
  ['Hair & Skin Glow', '$175', 'Skin Glow offers a rejuvenating skincare treatment designed to enhance your natural radiance. Utilizing high-quality ingredients, it deeply nourishes the skin, leaving it luminous and revitalized.'],
  ['Hair, Skin and Nails', '$175', 'Hair, Skin and Nails services focus on enhancing your natural beauty through a blend of essential nutrients like magnesium, taurine, and a comprehensive vitamin complex. This carefully crafted formula supports healthy hair growth, glowing skin, and strong nails, helping you achieve a vibrant and radiant appearance.'],
  ['Hangover', '$175', "The Hangover service offers a thorough recovery solution designed to combat symptoms through a potent blend of essential vitamins and hydration. Our treatment includes B Complex, Lactated Ringer's, Toradol, Zofran, and Hydroxycobalamin, all aimed at restoring your well-being effectively."],
  ['Immunity', '$150', "Immunity services focus on enhancing your body's defenses through a powerful blend of Zinc, Vita Complex, and Ascorbic Acid. This combination works synergistically to support overall health, boost immune function, and promote vitality."],
  ['Inner Beauty', '$175', 'Inner Beauty offers a rejuvenating blend of ascorbic acid, a vitamin complex, and biotin, all expertly formulated in 1000 ml of normal saline. This nourishing infusion is designed to enhance your natural glow, promoting overall wellness and vitality from within.'],
  ['Jet Lag IV', '$185', 'Jet Lag IV therapy offers a specialized infusion designed to combat the symptoms of jet lag, helping to restore hydration and replenish essential nutrients. This treatment aims to enhance recovery and improve overall well-being after long flights, allowing you to feel revitalized and ready for your destination.'],
  ['Lactated Ringers', '$115', "Lactated Ringer's solution is a sterile intravenous fluid used for fluid and electrolyte replenishment in patients. It contains a balanced mixture of electrolytes that helps restore hydration and maintain acid-base balance in the body."],
  ['Myers Cocktail', '$185', 'The Myers Cocktail is a nutrient-rich intravenous therapy that combines vitamins and minerals to enhance overall wellness and boost energy levels. This treatment is often used to alleviate symptoms of fatigue, migraines, and dehydration.'],
  ['NAD+ 250mg', '$150', 'NAD+ services focus on enhancing cellular energy production and promoting overall wellness through intravenous therapy. By replenishing this vital coenzyme, clients may experience improved metabolism, increased mental clarity, and better physical performance. (This is a 2.5 hour infusion)'],
  ['NAD+ 500 mg', '$275', 'NAD+ 500 mg is a dietary supplement designed to enhance cellular energy production while supporting overall metabolic health through the replenishment of essential coenzymes. This specific formulation not only promotes healthy aging but also has the potential to improve cognitive performance, making it an important addition to your daily wellness routine. By incorporating NAD+ 500 mg into your regimen, you can experience increased vitality and a boost in mental clarity. (This is a 4 hour infusion)'],
  ['Normal Saline', '$115', 'Normal Saline is a sterile solution of sodium chloride in water, commonly used for hydration and to restore electrolyte balance in patients. It serves as a versatile intravenous fluid in medical settings, facilitating the administration of medications and cleaning wounds.'],
  ['Post Surgery', '$140', 'Our postoperative IV includes a double dose of Vitamin C, B-Complex, Zinc, and anti-nausea medication. What is included: Vitamin C, B Complex, Zinc, Zofran.'],
  ['Quench', '$135', "Quench offers a unique service that allows you to draw 2 ml from each vial of essential nutrients, including Ascorbic Acid, Vita Complex, and Mineral Blend. This customizable approach helps replenish your body's vital elements, promoting overall health and well-being."],
  ['Reboot', '$125', 'Reboot involves Ondansetron, Vita Complex, and Mineral Blend, which are then injected into a 1000ml normal saline (NS) bag. This service is designed to enhance hydration and support wellness through a tailored blend of essential nutrients and medications.'],
  ['Recovery & Performance', '$140', 'Recovery & Performance offers a specialized IV therapy that involves drawing 1-3ml from each selected vial, including Ascorbic Acid, Vita Complex, Mineral Blend, and Amino Blend, and injecting them into a 1000ml normal saline IV bag. This tailored blend aims to enhance recovery and improve overall performance by delivering essential nutrients directly into the bloodstream.'],
  ['Snownbright Skin Rejuvenation', '$175', 'Snownbright Skin Rejuvenation utilizes a powerful blend of ascorbic acid, glutathione, and alpha-lipoic acid delivered in a 1000 ml saline solution to enhance skin vitality and promote a youthful appearance. This treatment helps to brighten skin tone, reduce signs of aging, and improve overall skin texture for a radiant glow.'],
  ['Stomach Flu', '$150', 'Stomach Flu services provide relief and management options for individuals experiencing gastrointestinal distress. Our offerings include Zofran for nausea, Vita Complex for vitamin replenishment, and Dexpanthenol to support gut health and recovery.'],
  ['The Baller', '$215', 'The Baller service offers a powerful blend of nutrients, including Myers Cocktail, B complex vitamins, magnesium, calcium, and toradol, designed to enhance overall wellness and vitality. This comprehensive infusion supports hydration, boosts energy levels, and promotes recovery from fatigue and discomfort.'],
  ['Timeless', '$185', 'Timeless offers a specialized infusion blend featuring hydroxocobalamin, magnesium chloride, vita complex, and N-acetylcysteine, all combined in 1000 ml of normal saline. This unique formulation is designed to enhance overall wellness and provide essential nutrients for optimal health.'],
  ['Work out boost', '$150', 'Work Out Boost is a powerful supplement designed to enhance your workout performance with a blend of essential ingredients, including an amino blend, B vitamins, biotin, glutathione (IVP), and lysine. This unique combination supports muscle recovery, energy production, and overall endurance, helping you achieve your fitness goals more effectively.'],
];

export default function IvHydrationPage() {
  return (<><PageHero image='https://galaxy-prod.tlcdn.com/gen/5b6600bfdfad44a4ad5a979492f3e84f.jpeg' title='IV Hydration & Add-Ons' description='Concierge IV therapy delivered wherever you are.' /><FinancingBanner /><section className='mx-auto max-w-7xl px-6 py-16'><p className='text-center text-sm font-bold uppercase tracking-widest text-copper'>Our IV Menu</p><h2 className='mt-2 text-center font-serif text-3xl font-bold text-navy'>Find the Blend That's Right for You</h2><div className='mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3'>{ivMenu.map(([name, price, desc]) => (<div key={name} className='flex flex-col rounded-2xl border border-cream-dark bg-white p-6 shadow-sm'><h3 className='font-serif text-xl font-bold text-navy'>{name}</h3><p className='mt-3 text-2xl font-bold text-copper'>{price}</p><p className='mt-3 flex-1 text-sm text-gray-600'>{desc}</p><BookNowButton className='mt-5 self-start' /></div>))}</div></section><BookingSection closingHeadline='Ready to Feel Your Best?' /></>);
}