import FinancingBanner from '@/components/financing-banner'; import PageHero from '@/components/page-hero'; import BookNowButton from '@/components/book-now-button'; import BookingSection from '@/components/booking-section';

const injections = [
  ['Acetylcysteine', '—', '$25'],
  ['Alpha Lipoic Acid', '—', '$25'],
  ['Amino Blend', '—', '$30'],
  ['Ascorbic Acid', '—', '$30'],
  ['B12', '—', '$25'],
  ['Battery Pack B12+B-Complex', '—', '$40'],
  ['B-Complex', '—', '$25'],
  ['Biotin', '0.5 mg/ml', '$30'],
  ['Biotin', '10 mg/ml', '$40'],
  ['Boost (B12, B Complex, Glutathione)', '—', '$60'],
  ['Calcium Gluconate', '—', '$25'],
  ['Compazine', '—', '$35'],
  ['CoQ10 (Coenzyme 10)', '—', '$40'],
  ['Dexamethasone', '4 mg', '$50'],
  ['Dexpanthenol', '—', '$25'],
  ['Diphenhydramine', '—', '$25'],
  ['Famotidine (Pepcid)', '—', '$30'],
  ['Folic Acid', '—', '$45'],
  ['Gluthatione Injection', '—', '$30'],
  ['Hair Repair', '—', '$115'],
  ['L-Argenine', '—', '$25'],
  ['L-Carnitine', '—', '$25'],
  ['L-Lysine', '—', '$25'],
  ['L-Glutamine', '—', '$25'],
  ['L-Tourine', '—', '$30'],
  ['Magnesium Chloride', '—', '$25'],
  ['MICC', '—', '$50'],
  ['MICC Wt Loss', '—', '$75'],
  ['Mineral Blend', '—', '$30'],
  ['NAD+ 250 mg', '250 mg', '$115'],
  ['NAD+ 500 mg', '500 mg', '$150'],
  ['Phenergan', '—', '$40'],
  ['Phenylephrine', '—', '$25'],
  ['PMS Releif', '—', '$45'],
  ['Pyridoxine', '—', '$25'],
  ['Reglan', '—', '$35'],
  ['Toradol', '30 mg', '$40'],
  ['Toradol', '60 mg', '$50'],
  ['Thiamine', '—', '$35'],
  ['Tri Immune Booster', '—', '$35'],
  ['Vita Complex', '—', '$35'],
  ['Vitamin D3 - IM', '1 ml', '$40'],
  ['Zinc', '—', '$25'],
  ['Zofran', '2 mg', '$30'],
  ['Zofran', '4 mg', '$40'],
];

export default function InjectionsPage() {
  return (<><PageHero image='https://galaxy-prod.tlcdn.com/gen/de19b3bf74744985925597c493630930.jpeg' title='Wellness Injections' description='Add a boost to any IV or book a standalone injection.' /><FinancingBanner /><section className='mx-auto max-w-5xl px-6 py-16'><p className='text-center text-sm font-bold uppercase tracking-widest text-copper'>Injection Menu</p><h2 className='mt-2 text-center font-serif text-3xl font-bold text-navy'>Priced & Ready to Add</h2><div className='mt-10 overflow-hidden rounded-2xl border border-cream-dark bg-white'><div className='grid grid-cols-[1fr_120px_100px] bg-navy px-6 py-4 text-sm font-bold uppercase tracking-wider text-white'><span>Medication</span><span>Dose</span><span className='text-right'>Price</span></div>{injections.map(([name, dose, price], i) => (<div key={name + dose} className={`grid grid-cols-[1fr_120px_100px] items-center px-6 py-4 ${i % 2 === 0 ? 'bg-white' : 'bg-cream'}`}><span className='font-semibold text-navy'>{name}</span><span className='text-sm text-gray-600'>{dose}</span><span className='text-right font-bold text-copper'>{price}</span></div>))}</div><div className='mt-8 text-center'><BookNowButton /></div></section><BookingSection closingHeadline='Boost Your Wellness Today' /></>); }