import FinancingBanner from '@/components/financing-banner'; import PageHero from '@/components/page-hero'; import BookNowButton from '@/components/book-now-button'; import BookingSection from '@/components/booking-section';

const injections = [
  ['Acetylcysteine', '200 mg/ml', '$25'],
  ['Alpha Lipoic Acid', '25 mg/ml', '$25'],
  ['Amino Blend', 'L-Proline 50mg, L-Arginine HCL 100mg, L-Lysine HCL 50mg, L-Carnitine 100mg per ml', '$30'],
  ['Ascorbic Acid', '500 mg/ml', '$30'],
  ['B12 (Cyanocobalamin)', '30,000 mcg/ml', '$25'],
  ['Battery Pack B12+B-Complex', '—', '$40'],
  ['B-Complex (Vita Complex)', 'B1 100MG/B2 2MG/B3 100MG/B5 2MG/B6 2MG per ml', '$25'],
  ['Biotin', '0.5 mg/ml', '$30'],
  ['Biotin', '10 mg/ml', '$40'],
  ['Boost (B12, B Complex, Glutathione)', '—', '$60'],
  ['Calcium Gluconate', '100 mg/ml', '$25'],
  ['Compazine', '10 mg/2 ml', '$35'],
  ['CoQ10 (Coenzyme 10)', '20 mg/ml', '$40'],
  ['Dexamethasone', '4 mg/ml', '$50'],
  ['Dexpanthenol', '250 mg/ml', '$25'],
  ['Diphenhydramine', '50 mg/ml', '$25'],
  ['Famotidine (Pepcid)', '10 mg/ml', '$30'],
  ['Folic Acid', '5 mg/ml', '$45'],
  ['Gluthatione Injection', '200 mg/ml', '$30'],
  ['Hair Repair', '—', '$115'],
  ['L-Argenine', '200 mg/ml', '$25'],
  ['L-Carnitine', '500 mg/ml', '$25'],
  ['L-Lysine', '100 mg/ml', '$25'],
  ['L-Glutamine', '25 mg/ml', '$25'],
  ['L-Tourine', '50 mg/ml', '$30'],
  ['Magnesium Chloride', '300 mg/ml', '$25'],
  ['MICC', 'Methionine 25mg, Inositol 50mg, Choline 50mg, Cyanocobalamin 330 mcg', '$50'],
  ['MICC Wt Loss', '—', '$75'],
  ['Mineral Blend', 'Magnesium 80mg, Zinc 1mg, Manganese 0.02mg, Copper 0.2mg', '$30'],
  ['NAD+ 250 mg', '100 mg/ml', '$115'],
  ['NAD+ 500 mg', '100 mg/ml', '$150'],
  ['Phenergan', '25 mg/ml', '$40'],
  ['Phenylephrine', '10 mg/ml', '$25'],
  ['PMS Releif', '—', '$45'],
  ['Pyridoxine', '85 mg/ml', '$25'],
  ['Reglan', '10 mg/2 ml', '$35'],
  ['Toradol', '30 mg/ml', '$40'],
  ['Toradol', '60 mg/2 ml', '$50'],
  ['Thiamine', '200 mg/2 ml', '$35'],
  ['Tri Immune Boost', 'Ascorbic Acid 200mg/mL, Glutathione 200mg/mL, Zinc Sulfate 2.5mg/mL', '$35'],
  ['Vita Complex', 'B1 100MG/B2 2MG/B3 100MG/B5 2MG/B6 2MG per ml', '$35'],
  ['Vitamin D3 - IM', '50,000 IU/ml or 1.25 mg/ml', '$40'],
  ['Zinc', '10 mg/ml', '$25'],
  ['Zofran IV', '1 mg/ml', '$30'],
  ['Zofran ODT', '4 mg', '$40'],
];

export default function InjectionsPage() {
  return (<><PageHero image='https://galaxy-prod.tlcdn.com/gen/de19b3bf74744985925597c493630930.jpeg' title='Wellness Injections' description='Add a boost to any IV or book a standalone injection.' /><FinancingBanner /><section className='mx-auto max-w-5xl px-6 py-16'><p className='text-center text-sm font-bold uppercase tracking-widest text-copper'>Injection Menu</p><h2 className='mt-2 text-center font-serif text-3xl font-bold text-navy'>Priced & Ready to Add</h2><div className='mt-10 overflow-hidden rounded-2xl border border-cream-dark bg-white'><div className='grid grid-cols-[1fr_120px_100px] bg-navy px-6 py-4 text-sm font-bold uppercase tracking-wider text-white'><span>Medication</span><span>Dose</span><span className='text-right'>Price</span></div>{injections.map(([name, dose, price], i) => (<div key={name + dose} className={`grid grid-cols-[1fr_120px_100px] items-center px-6 py-4 ${i % 2 === 0 ? 'bg-white' : 'bg-cream'}`}><span className='font-semibold text-navy'>{name}</span><span className='text-sm text-gray-600'>{dose}</span><span className='text-right font-bold text-copper'>{price}</span></div>))}</div><div className='mt-8 text-center'><BookNowButton /></div></section><BookingSection closingHeadline='Boost Your Wellness Today' /></>); }